---
apiVersion: v1
kind: List
items:
{{- range .Values.ConfigMap }}
- apiVersion: v1
  kind: ConfigMap
  metadata:
    labels:
{{ include "configmap.labels.chart" $ | indent 6 }}
  {{- if .labels }}
{{ toYaml .labels | indent 6 }}
  {{- end }}
  {{- if .annotations }}
    annotations:
{{ toYaml .annotations | indent 6 -}}
  {{- end }}
    name: {{ .name }}
  data:
  {{- if .data }}
{{ toYaml .data | indent 4 -}}
  {{- end }}
{{- end }}
